---
title: lanark.house
timezone: America/Edmonton
collections:
  grievances:
    title: Grievances
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: |
  This repository and site serve as a way to document and
  inventory every step of my new home purchase process.
baseurl: "/"
url: https://lanark.house
plugins:
- jekyll-remote-theme
- jekyll-sitemap
remote_theme: daviddarnes/garth
exclude:
  - "uploads/Contract - Tuesday at 1-47 PM.m4a"
