name: Create transparency report

on:
  schedule:
    - cron: 0 */3 * * *
  workflow_dispatch:
  push:
    paths: [.github/workflows/transparency.yaml]

jobs:
  audit-pdf:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: screenshot listing page
        uses: karol-brejna-i/webpage-screenshot-action@94dd5ca598dcb80be94d5d2c6ad87d550ebbfa48
        with:
          url: https://douglashomes.net/new-home/fernie-3-2/
          mode: wholePage
          output: _uploads/fernie-3-2.png
      - name: screenshot lanark landing contact page
        uses: karol-brejna-i/webpage-screenshot-action@94dd5ca598dcb80be94d5d2c6ad87d550ebbfa48
        with:
          url: https://douglashomes.net/airdrie/lanark-landing/
          mode: element
          output: _uploads/lanark-landing.png
          selector: '#showhome > div'
      - name: screenshot warranty limits
        uses: karol-brejna-i/webpage-screenshot-action@94dd5ca598dcb80be94d5d2c6ad87d550ebbfa48
        with:
          url: https://anhwp.com/homeowners/owning-your-new-home/new-home-warranty/
          mode: element
          output: _uploads/anhwp-new-home-warranty.png
          selector: .fusion-text-6
      - name: audit the PDF
        working-directory: _uploads
        run: |
          curl -LO --silent https://douglashomes.net/wp-content/uploads/2024/08/Fernie-204LWC.pdf
          curl -LO --silent https://douglashomes.net/wp-content/uploads/2024/08/Fernie-204LWC-1.pdf
          curl -LO --silent https://douglashomes.net/wp-content/uploads/2024/08/Fernie-204LWC-2.pdf
          curl -LO --silent https://douglashomes.net/wp-content/uploads/2024/08/Fernie-204LWC-3.pdf
          sha256sum Fernie-204LWC.pdf >> $GITHUB_STEP_SUMMARY
      - uses: actions/attest-build-provenance@bd77c077858b8d561b7a36cbe48ef4cc642ca39d # v2.2.2
        with:
          subject-path: '.github/workflows/transparency.yaml, _uploads/**'
      - name: Commit & Push changes
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'updating the lanark landing listing @ 204 Langwell Common SE'
